name: 🛠️ Compile Release Assets

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ['386', amd64, arm64]
        exclude:
          - goarch: '386'
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compile Go binaries
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: '1.26.3'
        project_path: './cmd/server'
        binary_name: who-dat
        md5sum: true
        extra_files: LICENSE
